spring:
  application:
    name: news

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/news}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:131072}


  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
server:
  port: 8090